name: oidc
on: [push]
jobs:

  oidc-initiating-workflow:
    name: OIDC Token from Initiating Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Request OIDC Token
        run: |
          # Need to base64-encode this to work-around GHA secret redaction
          echo "ACTIONS_ID_TOKEN_REQUEST_TOKEN (base64-encoded)"
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | base64
          # Request token
          curl "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sigstore" \
            -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            -H "Accept: application/json; api-version=2.0" \
            -H "Content-Type: application/json" \
            --silent | jq -r '.value' > oidc_token
          echo -e "\nOIDC Token (base64-encoded)"
          cat oidc_token | base64
          echo -e "\nOIDC Token (decoded)"
          cat oidc_token | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'


  oidc-reusable-workflow:
    uses: bdehamer/workflows/.github/workflows/oidc-dump.yml@main
    with:
      greeting: "hello world"
